version: '3.8'

services:
  client:
    build: .
    deploy:
      replicas: 10
    # host.docker.internal works on Docker Desktop for Windows/Mac
    extra_hosts:
      - "host.docker.internal:host-gateway" 
# 